name = "pablo-news"
main = "src/index.ts"
compatibility_date = "2025-04-01"

routes = [
  { pattern = "news.renezhou.com", custom_domain = true }
]

kv_namespaces = [
  { binding = "BRIEFINGS", id = "cc113354825c4497b39a2fd99684a17d" }
]
